### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Louis-7** [vularsoft/rxeditor#4]
类似的项目我之前做过，web端的设计器。

当时遇到不少的坑。 一定要想好这个应用的定位，千万别弄成开发者不爱用，不懂技术的人想设计又觉得功能不够的尴尬境地。

希望你的项目成功！！！加油！！！

**Comment by vularsoft** [comment]
对的，就是有这样的问题。我现在也在思考这个问题，最初做的时候没考虑这么多。初步定位，不给技术人员用，后面会封装代码相关细节，界面尽量少暴露细节。非常感谢！

**Comment by Louis-7** [comment]
客气了。

建议只做一些原型开发，这样不懂技术的人设计完之后开发人员也可以在你生成的项目的基础上再进行开发（理想状况）。 如果你的项目cover了很多开发中的流程，后期的维护成本会很高，至少我是这么认为的。

**Comment by vularsoft** [comment]
好的，非常感谢

**Comment by saltbo** [comment]
昨天还在想有没有类似的轮子，今天就刷到了。

我的想法是：不要做成Dreamweaver！  要现代化一些。

**Comment by vularsoft** [comment]
> 昨天还在想有没有类似的轮子，今天就刷到了。
> 
> 我的想法是：不要做成Dreamweaver！ 要现代化一些。

有需求场景吗？功能方面的现代化吗？

**Comment by saltbo** [comment]
我的设想是：设计人员使用它来设计，但是背后不能是单纯的html，要是vue格式的模板。 

bootstrap换成bulma。 这样，设计完成，前端就可以直接在这个基础上接入数据了

**Comment by saltbo** [comment]
另外就是 现在的编辑器操作台繁琐，得做成processon那样的

**Comment by vularsoft** [comment]
代码生成可以生成任何格式，我觉得给开发人员用，有点傲慢了。

**Comment by vularsoft** [comment]
开发人员技术都很厉害，要求也高

**Comment by vularsoft** [comment]
processon 是用js 的canvas做的吧？我这个是用CSS样式实现的

**Comment by saltbo** [comment]
哎 你加油吧 我也就想想 这东西真要按我的目标做 编辑器的复杂度会很高

**Comment by vularsoft** [comment]
> 哎 你加油吧 我也就想想 这东西真要按我的目标做 编辑器的复杂度会很高

好的，非常感谢关注

**Comment by saltbo** [comment]
话说 你的服务器是打挂了么 访问好慢

还不如部署在GitHubPages

**Comment by vularsoft** [comment]
我买的阿里云服务器，今天来的流量多了，有点撑不住

**Comment by Louis-7** [comment]
我是跟着大佬的star过来的，这项目要火。哈哈

**Comment by vularsoft** [comment]
哪个大佬star了我啊？这只是个半成品

**Comment by saltbo** [comment]
知乎还是挺牛逼的么 我也要去知乎发文章了

**Comment by vularsoft** [comment]
> 知乎还是挺牛逼的么 我也要去知乎发文章了

快去吧

**Comment by Louis-7** [comment]
> 哪个大佬star了我啊？这只是个半成品

廖雪峰

**Comment by vularsoft** [comment]
> > 哪个大佬star了我啊？这只是个半成品
> 
> 廖雪峰

廖老师在知乎上回答了我，github上他也有帐号吗？

**Comment by Louis-7** [comment]
@vularsoft michaelliao

**Comment by vularsoft** [comment]
谢谢


> @vularsoft michaelliao

谢谢

**Comment by firebear-ssl** [comment]
请教一下，如何将从服务器取回的HTML代码，设定到可视化设计界面与代码输入栏显示。
