### ISSUE TITLE
拖拽的控件，如果想加一些默认的设置，如class\href\src等，修改那个地方比较何适呢？

### ISSUE THREAD

**Issue by firebear-ssl** [vularsoft/rxeditor#6]
拖拽的控件，如果想加一些默认的设置，如class\href\src等，修改那个地方比较何适呢？

**Comment by vularsoft** [comment]
拖拽的控件传入的是HTML代码，直接在HTML代码里面添加就行，这代码可以从后台读取，模拟AP在api目录下的toolbox文件

**Comment by vularsoft** [comment]
你还可以添加你自己喜欢的控件代码

**Comment by firebear-ssl** [comment]
解决了！要否加个微信？我的是firebear，方便的话加一下。我这边研发各类产品，会有很多合作机会。

**Comment by vularsoft** [comment]
解决了就好，我加你
